apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-12T19:00:02Z"
  labels:
    app: aiweb
  name: aiweb
spec:
  containers:
    - args:
        - nvidia-smi
        - -L
      image: localhost/sd_next:0.3
      name: sdnext
      ports:
        - containerPort: 7860
          hostPort: 7860
        - containerPort: 11434
          hostPort: 11434
      securityContext:
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /sdnext/automatic/models
          name: models-pvc
    - args:
        - serve
      image: docker.io/ollama/ollama:latest
      name: ollama
      securityContext:
        seLinuxOptions:
          type: spc_t
      volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-pvc
  volumes:
    - name: ollama-pvc
      persistentVolumeClaim:
        claimName: ollama
    - name: models-pvc
      persistentVolumeClaim:
        claimName: models