apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-07-13T11:42:30Z"
  labels:
    app: webapps
  name: webapps
spec:
  containers:
    - env:
        - name: OLLAMA_BASE_URL
          value: ${OLLAMA_BASE_URL}
      image: ghcr.io/open-webui/open-webui:main
      name: open-webui
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 3000
          hostPort: 3000
        - containerPort: 81
          hostPort: 8081
      securityContext: {}
      volumeMounts:
        - mountPath: /app/backend/data
          name: open-webui-pvc
    - image: docker.io/jc21/nginx-proxy-manager:latest
      name: nginx
      volumeMounts:
        - mountPath: /data
          name: nginx-data-pvc
        - mountPath: /etc/letsencrypt
          name: nginx-letsencrypt-pvc
  volumes:
    - name: open-webui-pvc
      persistentVolumeClaim:
        claimName: open-webui
    - name: nginx-data-pvc
      persistentVolumeClaim:
        claimName: nginx-data
    - name: nginx-letsencrypt-pvc
      persistentVolumeClaim:
        claimName: nginx-letsencrypt