# Use the base image with CUDA 12.5.0 runtime on Ubuntu 22.04
FROM nvidia/cuda:12.5.0-runtime-ubuntu22.04

# Set author label
LABEL author="dan@thewisemans.io"

# Default working directory
WORKDIR /

# Replace the default shell with bash
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# Update and upgrade system packages, install required tools and dependencies
RUN apt update && \
    apt -y upgrade && \
    apt install -y --no-install-recommends \
    git python3 python3.10-venv && \
    useradd sdnext && \
    mkdir /sdnext

# Copy the start script to the container and set ownership/permissions
COPY ./start.sh /kohya/start.sh
COPY ./accelerate.yaml /kohya/accelerate.yaml


RUN chown -R kohya:kohya /kohya && \
    chmod +x /kohya/start.sh

# Switch to the newly created user
USER kohya

# Set working directory for the user
WORKDIR /kohya

RUN ln -s /dependencies/start.sh start.sh &&\
    chmod +x /start.sh && \
    git clone https://github.com/bmaltais/kohya_ss.git /kohya_ss && \
    cd ./kohya_ss && \
    python3 -m venv venv && \
    source venv/bin/activate && \
    pip3 install wheel && \
    pip3 install torch torchvision

# Entrypoint command to run the start script
ENTRYPOINT ["/bin/bash", "/kohya/start.sh"]





